version: "3.9"

services:
  api:
    build:
      dockerfile: docker/Dockerfile
      context: .
    environment:
      ENVIRONMENT: prod
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  api-test:
    build:
      dockerfile: docker/Dockerfile
      context: .
    entrypoint: "gradle test"
    environment:
      ENVIRONMENT: test
    depends_on:
      - mongodb

  mongodb:
    image: "mongo:4.4.6"

