version: "3.9"

services:
  api:
    build:
      dockerfile: docker/service.dockerfile
      context: .
    environment:
      spring_profiles_active: docker
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    links:
      - mongodb

  api-test:
    build:
      dockerfile: docker/test.dockerfile
      context: .
    environment:
      spring_profiles_active: test
    volumes:
      - .gradle:/home/gradle:delegated
    depends_on:
      - api
    links:
      - api

  mongodb:
    image: "mongo:4.4.6"
    ports:
      - 27017:27017

