spring:
  data:
    mongodb:
      database: "machine_metrics"
      host: "localhost"

app:
  defaultLastMinutesStatistics: 10
  seedMachineFile: "docs/seed/machines.csv"
  seedParametersFile: "docs/seed/parameters.csv"

logging:
  level:
    - debug
    - org.springframework.data.mongodb.core.ReactiveMongoTemplate: debug
    - org.springframework.data.mongodb.repository.query: debug
