spring:
  data:
    mongodb:
      database: "machine_metrics"
      host: "mongodb"

app:
  defaultLastMinutesStatistics: 10
  seedMachineFile: "resources/seed/machines.csv"
  seedParametersFile: "resources/seed/parameters.csv"

logging:
  level:
    - debug
    - org.springframework.data.mongodb.core.ReactiveMongoTemplate: debug
    - org.springframework.data.mongodb.repository.query: debug
